require('options')
require('packer-config')
--require("colors-config.nightfox")
vim.cmd("colorscheme nordfox")
require('nvim-tree-config')
require("keymap-config")
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('whichkey-config')
require('toggleterm-config')
require('autopairs-config')
require('telescope-config')
require("lsp-config.language-servers")
require("lsp-config.lspsaga")
require("lsp-config.cmp")
require("lsp-config.null-ls")
require("lsp-config.lspkind")
require("lsp-config.mason")


